name = "blog-admin"
main = "src/index.js"
compatibility_date = "2023-12-01"
account_id = "16591313e1d38f33215ef81bda994f80"

[vars]
GITHUB_OWNER = "ImUpXuu"
GITHUB_REPO = "xuhome"
GITHUB_BRANCH = "main"
POSTS_PATH = "src/content/posts"
TALK_OWNER = "ImUpXuu"
TALK_REPO = "xuhome"
TALK_BRANCH = "main"
TALK_PATH = "src/content/talks"
IMAGE_PATH = "public/images"
BLOG_URL = "https://upxuu.com"
PHOTO_OWNER = "ImUpXuu"
PHOTO_REPO = "photo"
PHOTO_BRANCH = "main"
PHOTO_PATH = "images"
PROXY_BASE = "https://edit.upxuu.com/img"
